spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${PROD_DB_ENDPOINT}:3306/${PROD_DB_NAME}?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 10000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: create # 맨 처음만 create하고, 이후는 none으로 변경
    open-in-view: false
    defer-datasource-initialization: true

logging:
  level:
    root: INFO
